{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-app-chart.fullname" . }}
  labels:
    {{- include "generic-app-chart.labels" . | nindent 4 }}
  {{- with (include "generic-app-chart.annotations" .) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
data:
  {{- toYaml .Values.config | nindent 2 }}
{{- end }}
