apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app-chart.fullname" . }}
  labels:
    {{- include "generic-app-chart.labels" . | nindent 4 }}
  {{- with (include "generic-app-chart.serviceAnnotations" .) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "generic-app-chart.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
